### PR TITLE
Feature/start charging

### LINKED ISSUE #45: EV Start/Stop Charging
## EV Start/Stop Charging

> As an owner of an **electric vehicle**
> I want to be able to **remotely turn on or off** the vehicle’s **charger**
> so that I can **control the charging of my vehicle**.

### Acceptance criteria

- Remotely turn on EV charging
- Remotely turn off EV charging
- Determine whether a charging cable is connected
- Determine the current state of the EV charger
- Determine the current charge level of the battery

### PR DESCRIPTION
**Pull request by RubenPuben7**

### CODE REVIEW

**Review by RubenPuben7 — COMMENTED** [review]
Builder Created, Uses Access Token

**Review by RubenPuben7 — COMMENTED** [review]
Uses Vin

**Review by RubenPuben7 — COMMENTED** [review]
Uses Device ID

**Review by RubenPuben7 — COMMENTED** [review]
cpToken - uses Vin

**Review by RubenPuben7 — COMMENTED** [review]
Get cpToken - uses UserId

**Review by RubenPuben7 — COMMENTED** [review]
Gets cpToken - uses Last Four of Vin

**Review by RubenPuben7 — COMMENTED** [review]
Gets cpToken - uses cpToken

**Review by WonkiDonk — APPROVED** [review]

**Pull request merged**
